---
- name: Supervisor - Add repository
  yum: name="{{ item }}" state=present
  with_items:
    - epel-release

- name: Supervisor - Install package
  yum: name="{{ item }}" state=present
  with_items:
    - supervisor

# In CentOS services are not enabled by default.
- name: Supervisor - Run service on system start
  service: name=supervisord enabled=yes

# In CentOS services are not started right after install by default.
- name: Supervisor - Ensure the service is running
  service: name=supervisord state=started
